#!/bin/sh
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
build_dir=$(mktemp -d)
trap 'rm -rf "$build_dir"' EXIT

cp "$script_dir/WeatherAetherThreeEntry.js" "$build_dir/entry.js"
cd "$build_dir"
npm init -y >/dev/null 2>&1
npm install --no-save --ignore-scripts three@0.185.1 esbuild@0.28.1 >/dev/null 2>&1
mkdir -p "$repo_dir/Resources/Wallpapers/WeatherAether/vendor"
./node_modules/.bin/esbuild entry.js \
  --bundle \
  --format=iife \
  --target=es2020 \
  --minify \
  --legal-comments=inline \
  --banner:js='/* Three.js 0.185.1 subset; generated by Tools/build-weather-three.sh */' \
  --outfile="$repo_dir/Resources/Wallpapers/WeatherAether/vendor/three-weather.min.js"
perl -pi -e 's/[ \t]+$//' "$repo_dir/Resources/Wallpapers/WeatherAether/vendor/three-weather.min.js"
cp node_modules/three/LICENSE "$repo_dir/Resources/Wallpapers/WeatherAether/vendor/THREE-LICENSE.txt"
